WebAppTupsi/Models/IRecipesService.cs
using System.Linq;
using System.Threading.Tasks;

namespace TopsyTurvyCakes.Models
{
    public interface IRecipesService
    {
        Task DeleteAsync(long id);
        Recipe Find(long id);
        Task<Recipe> FindAsync(long id);
        IQueryable<Recipe> GetAll(int? count = null, int? page = null);
        Task<Recipe[]> GetAllAsync(int? count = null, int? page = null);
        Task SaveAsync(Recipe recipe);
    }
}

WebAppTupsi/Models/Recipe.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using static System.Environment;

namespace TopsyTurvyCakes.Models
{
    public class Recipe
    {
        public long Id { get; set; }
        
        [Required]
        [StringLength(100, MinimumLength = 5,
           ErrorMessage = "Hey - you've gotta give a name between 5 and 100 characters long!")]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public string Directions { get; set; }

        [Required]
        public string Ingredients { get; set; }

        public IEnumerable<string> DirectionsList
        {
            get { return (Directions ?? string.Empty).Split(NewLine); }
        }

        public IEnumerable<string> IngredientsList
        {
            get { return (Ingredients ?? string.Empty).Split(NewLine); }
        }

        #region Image

        public byte[] Image { get; set; }

        public string ImageContentType { get; set; }

        public string GetInlineImageSrc ()
        {
            if (Image == null || ImageContentType == null)
                return null;

            var base64Image = System.Convert.ToBase64String(Image);
            return $"data:{ImageContentType};base64,{base64Image}";
        }

        public void SetImage(Microsoft.AspNetCore.Http.IFormFile file)
        {
            if (file == null)
                return;

            ImageContentType = file.ContentType;

            using (var stream = new System.IO.MemoryStream())
            {
                file.CopyTo(stream);
                Image = stream.ToArray();
            }
        }

        #endregion
    }
}

WebAppTupsi/Models/RecipesDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace TopsyTurvyCakes.Models
{
    public class RecipesDbContext : DbContext
    {
        public DbSet<Recipe> Recipes { get; set; }

        public RecipesDbContext(DbContextOptions<RecipesDbContext> options)
            : base(options)
        {
            this.EnsureSeedData();
        }
    }
}

WebAppTupsi/Models/RecipesService.cs
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace TopsyTurvyCakes.Models
{
    public class RecipesService : IRecipesService
    {
        private readonly RecipesDbContext _context;

        public RecipesService()
        {
            var options = new DbContextOptionsBuilder<RecipesDbContext>()
                .UseInMemoryDatabase("TopsyTurvyCakes")
                .Options;

            _context = new RecipesDbContext(options);
        }

        public RecipesService(RecipesDbContext context)
        {
            _context = context;
        }

        public async Task DeleteAsync(long id)
        {
            _context.Recipes.Remove(new Recipe { Id = id });
            await _context.SaveChangesAsync();
        }

        public Recipe Find(long id)
        {
            return _context.Recipes.FirstOrDefault(x => x.Id == id);
        }

        public Task<Recipe> FindAsync(long id)
        {
            return _context.Recipes.FirstOrDefaultAsync(x => x.Id == id);
        }

        public IQueryable<Recipe> GetAll(int? count = null, int? page = null)
        {
            var actualCount = count.GetValueOrDefault(10);

            return _context.Recipes
                    .Skip(actualCount * page.GetValueOrDefault(0))
                    .Take(actualCount);
        }

        public Task<Recipe[]> GetAllAsync(int? count = null, int? page = null)
        {
            return GetAll(count, page).ToArrayAsync();
        }

        public async Task SaveAsync(Recipe recipe)
        {
            var isNew = recipe.Id == default(long);

            _context.Entry(recipe).State = isNew ? EntityState.Added : EntityState.Modified;

            await _context.SaveChangesAsync();
        }
    }
}

WebAppTupsi/Pages/Account/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TopsyTurvyCakes.Pages.Account
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        [Required]
        [Display(Name = "Email Address")]
        public string EmailAddress { get; set; }

        [BindProperty]
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public IActionResult OnPost()
        {
            var isValidUser =
                   EmailAddress == "admin@top.com"
                && Password == "123456";

            if (!isValidUser)
            {
                ModelState.AddModelError("", "Invalid username or password!");
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            var scheme = CookieAuthenticationDefaults.AuthenticationScheme;

            var user = new ClaimsPrincipal(
                new ClaimsIdentity(
                        new[] { new Claim(ClaimTypes.Name, EmailAddress) },
                        scheme
                    )
                );

            return SignIn(user, scheme);
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToPage("/Index");
        }
    }
}

WebAppTupsi/Pages/Account/Profile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TopsyTurvyCakes.Pages.Account
{
    public class ProfileModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

WebAppTupsi/Pages/Admin/AddEditRecipe.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TopsyTurvyCakes.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace TopsyTurvyCakes.Pages.Admin
{
    [Authorize]
    public class AddEditRecipeModel : PageModel
    {
        private readonly IRecipesService recipesService;

        [FromRoute]
        public long? Id { get; set; }

        public bool IsNewRecipe
        {
            get { return Id == null; }
        }

        [BindProperty]
        public Recipe Recipe { get; set; }
        [BindProperty]
        public IFormFile Image { get; set; }

        public AddEditRecipeModel(IRecipesService recipesService)
        {
            this.recipesService = recipesService;
        }

        public async Task OnGetAsync()
        {
            Recipe = await recipesService.FindAsync(Id.GetValueOrDefault())
                ?? new Recipe();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            try
            {
                if(!ModelState.IsValid)
                    return Page();

                Recipe.Id = Id.GetValueOrDefault();
                var _recipe = await recipesService.FindAsync(Id.GetValueOrDefault());
                _recipe.Ingredients = Recipe.Ingredients;
                _recipe.Name = Recipe.Name;
                _recipe.Description = Recipe.Description;
                _recipe.Directions = Recipe.Directions;

                if (Image != null)
                    _recipe.SetImage(Image);
                else
                    _recipe.Image = Recipe.Image;

                await recipesService.SaveAsync(_recipe);

                return RedirectToPage("/Recipe", new { id = Id });
            }
            catch
            {
                return null;
            }
        }

        public async Task<IActionResult> OnPostDelete()
        {
            var DeletedID = Id.GetValueOrDefault();
            await recipesService.DeleteAsync(DeletedID);
            return RedirectToPage("/Index");
        }



    }
}

WebAppTupsi/Pages/Admin/AddEditRecipe.cshtml
@page "{Id?}"

@model AddEditRecipeModel
@{
    ViewData["Title"] = Model.IsNewRecipe ? "New Recipe" : "Edit Recipe";
}

@if (!ModelState.IsValid)
{
    <div class="col-md-offset-2 col-md-10" >
        <h3 class="text-danger">Validation Error</h3>
        <div asp-validation-summary="All"> </div>
        <hr />
    </div>
}
    <form method="post" class="form-horizontal" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="Recipe.Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Recipe.Name" type="text" class="form-control" />
                <span asp-validation-for="Recipe.Name"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Recipe.Description" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea rows="3" asp-for="Recipe.Description" class="form-control"></textarea>
                <span asp-validation-for="Recipe.Description"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Recipe.Ingredients" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea rows="5" asp-for="Recipe.Ingredients" class="form-control"></textarea>
                <span asp-validation-for="Recipe.Ingredients"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Recipe.Directions" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea rows="5" asp-for="Recipe.Directions" class="form-control"></textarea>
                <span asp-validation-for="Recipe.Directions"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Recipe.Image" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input type="file"  asp-for="Image" class="form-control" />
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn btn-primary">Save</button>
                @if (!Model.IsNewRecipe)
                {
                    <button type="submit"
                            onclick="javascript: return confirm('Are you sure you want to delete?');"
                            asp-page-handler="Delete" class="btn btn btn-danger">
                        Delete
                    </button>
                }
            </div>
        </div>


    </form>